Repository Team-Delight/Delight-Server, pull requests merged in 2021-08, with the labels that each got.

#30 [#29] feat : 단일 태크를 통한 음식 검색 추가
  src/main/java/com/team/delightserver/config/QuerydslConfig.java
  src/main/java/com/team/delightserver/config/UpperCaseTableConfig.java
  src/main/java/com/team/delightserver/service/ApiFoodService.java
  src/main/java/com/team/delightserver/web/controller/ApiFoodController.java
  src/main/java/com/team/delightserver/web/domain/food/FoodRepository.java
  src/main/java/com/team/delightserver/web/domain/food/FoodRepositoryCustom.java
  src/main/java/com/team/delightserver/web/domain/food/FoodRepositoryImpl.java
  src/main/java/com/team/delightserver/web/domain/foodtag/FoodTag.java
  src/main/java/com/team/delightserver/web/domain/tag/Tag.java
  src/main/java/com/team/delightserver/web/dto/response/RecommendationRankResponse.java
  src/main/java/com/team/delightserver/web/dto/response/TagRelatedFoodsResponse.java
Labels: 개발, 우선순위 중, Doe, 완료

#77 Feature/#74 연관관계 변경에 따른 카테고리별 랭킹 조회 수정
  src/main/java/com/team/delightserver/service/ApiFoodRecommendationService.java
  src/main/java/com/team/delightserver/service/ApiMLRecommendationService.java
  src/main/java/com/team/delightserver/web/domain/foodrecommendation/FoodRecommendation.java
  src/main/java/com/team/delightserver/web/domain/foodrecommendation/FoodRecommendationRepository.java
  src/main/java/com/team/delightserver/web/domain/foodrecommendation/FoodRecommendationRepositoryImpl.java
  src/main/java/com/team/delightserver/web/domain/recommendation/Recommendation.java
  src/main/java/com/team/delightserver/web/domain/recommendation/RecommendationRepository.java
  src/main/java/com/team/delightserver/web/domain/recommendation/RecommendationRepositoryCustom.java
  src/main/java/com/team/delightserver/web/domain/recommendation/RecommendationRepositoryImpl.java
  src/main/java/com/team/delightserver/web/dto/response/RecommendationRankResponse.java
Labels: 우선순위 상, 수정, Min

#86 Feature/#81유저별 저장된 음식 정보 조회 기능
  build.gradle
  src/main/java/com/team/delightserver/service/ApiMypickService.java
  src/main/java/com/team/delightserver/service/ApiRecommendationService.java
  src/main/java/com/team/delightserver/web/controller/ApiMypickController.java
  src/main/java/com/team/delightserver/web/controller/ApiRecommendationController.java
  src/main/java/com/team/delightserver/web/domain/food/FoodRepositoryImpl.java
  src/main/java/com/team/delightserver/web/domain/mypick/MypickRepository.java
  src/main/java/com/team/delightserver/web/domain/mypick/MypickRepositoryCustom.java
  src/main/java/com/team/delightserver/web/domain/mypick/MypickRepositoryImpl.java
  src/main/java/com/team/delightserver/web/dto/response/MypickResponse.java
  src/main/java/com/team/delightserver/web/dto/response/TagRelatedFoodsResponse.java
Labels: 우선순위 상, 기능 개발, Min

#90 [#89] chore: response에 imgUrl 추가
  src/main/java/com/team/delightserver/web/domain/mypick/MypickRepositoryImpl.java
  src/main/java/com/team/delightserver/web/dto/response/MypickResponse.java
Labels: 우선순위 상, 기능 개발, Min
